### ISSUE TITLE
`sl pr`: `abort: not a Git repo`

### ISSUE THREAD

**Issue by alive** [facebook/sapling#202]
```
$ sl
  @  7d99579c2  20 minutes ago alive
  │  adding baz
  │
  o  80b8a88cb  20 minutes ago  alive
  │  adding bar
  │
  o  92ac78e5b  20 minutes ago  alive
  │  adding foo
  │
  o  9ffd396f8  21 minutes ago  alive
╭─╯  notes
│
o  7170a42fe  23 minutes ago  alive  remote/main
│  change
~
$ sl pr
abort: not a Git repo
```

I generated this sapling repo by `sl cloning` an existing git repo. There's no `.git` folder (which - I believe - is expected). Am I missing some setup here?
I'm able to use `gh` to create a pr in a normal git repository. Also, in `sl web`, I can see that the gh cli is auth'ed successfully.

**Comment by bolinfest** [comment]
Is this:

- a normal GitHub repo
- a GitHub enterprise repo
- other, please explain

**Comment by alive** [comment]
I think this just boils down to the use of ssh+a nontrivial ssh config. Do you plan on supporting ssh urls for this gh integration?

**Comment by bolinfest** [comment]
Yes, we are working on supporting ssh as the git protocol. Incidentally, here's an ssh-related fix that landed after the initial release:

https://github.com/facebook/sapling/commit/89d7a8aac3cb882960ec62bc81ea2c8c17d74de0

It is included in the new version we pushed today (20221116-203146-2c1a971a), so depending on your issue, that may help?

**Comment by whitevegagabriel** [comment]
I am experiencing the same result, though with a different config.

I cloned using https on a GitHub enterprise repo.

Should I create a separate issue?

**Comment by whitevegagabriel** [comment]
Welp, seems like github enterprise might just not be in the cards:
https://github.com/facebook/sapling/blob/595125ae8d4e4158fa49ea58126407d5a4e787e3/eden/scm/edenscm/ext/github/github_repo_util.py#L21

**Comment by alive** [comment]
> Yes, we are working on supporting ssh as the git protocol. Incidentally, here's an ssh-related fix that landed after the initial release:
> 
> [89d7a8a](https://github.com/facebook/sapling/commit/89d7a8aac3cb882960ec62bc81ea2c8c17d74de0)
> 
> It is included in the new version we pushed today (20221116-203146-2c1a971a), so depending on your issue, that may help?

Cool! this works for default ssh urls.

The other use case I have is different ssh hosts that are really just aliases for github.com (this is a common way to handle multiple github accounts)
For example, my `.ssh/config`
```
Host github-alive
   HostName github.com
   User git
   IdentityFile ~/.ssh/key1
```
Then my remote url is `github-alive/org/repo`
With this setup, I still get `abort: not a Git repo`

**Comment by alive** [comment]
I think, to fully support ssh urls `parse_owner_and_name_from_github_url` should first lookup the host in the ssh file as is decribed [here](https://stackoverflow.com/questions/59305574/given-the-alias-get-the-hostname-from-ssh-config). What do you think?

**Comment by nemith** [comment]
> I cloned using https on a GitHub enterprise repo.

GHE isn't supported and the message should state This is not a Github repo (meing github repo).  I reported this in #146 which actually should apply to github host or self hosted GHE instances.

**Comment by whitevegagabriel** [comment]
> @whitevegagabriel
>  
> > I cloned using https on a GitHub enterprise repo.
> 
> GHE isn't supported and the message should state This is not a Github repo (meing github repo).  I reported this in #146 which actually should apply to github host or self hosted GHE instances. 

Thanks, I'll be following #146!

**Comment by bolinfest** [comment]
@alive I believe this is fixed with this morning's release!
